CREATE TABLE courses (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    category ENUM('DEVELOPMENT', 'IA', 'FRONTEND', 'DATA', 'INNOVATION', 'MARKETING', 'DESIGN') NOT NULL
);